server:
  port: 5555

#actuator 모든 경로 노출
management:
  endpoints:
    web:
      exposure:
        include: "*"

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    com.springframework.web: WARN
    com.bloknoma: DEBUG

eureka:
  instance:
    prefer-ip-address: true # eureka 에 등록할 서비스의 이름을 host name 이 아닌 ip 주소로 등록
  client:
    register-with-eureka: true # eureka service 등록
    fetch-registry: true # eurek registry 캐싱
    service-url:
      defaultZone: http://locahost:8761/eureka/

#zuul:
#  prefix: /api
#  routes:
#    organizationservice: /organization/**

