server:
  port: 5555

#actuator 모든 경로 노출, zuul routes 경로 확인 위해서 필요
management:
  endpoints:
    web:
      exposure:
        include: "*"

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.bloknoma: DEBUG

eureka:
  instance:
    prefer-ip-address: true # eureka 에 등록할 서비스의 이름을 host name 이 아닌 ip 주소로 등록
  client:
    register-with-eureka: true # eureka service 등록
    fetch-registry: true # eurek registry 캐싱
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
#  ignored-services: '*' # eureka 에 등록된 서비스 경로 제외
  prefix: /api # 서비스 접두어 설정
  routes: # 수동 경로 매핑
    organizationservice: /organization/**
#    licensingservice: /licensing/**
#    licensestatic:
#      path: /licensestatic/** # 정적경로
#      serviceId: licensestatic # 리본 서비스 ID
##      url: http://licenseservice-static:8081 # 직접 호출 경로
#
#ribbon:
#  eureka:
#    enabled: false # 리본 유레카 지원 비활성화
#licensestatic:
#  ribbon:
#    listOfServers: http://licenseservice-static:8081, http://licenseservice-static2:8082


