server:
  port: 8888

spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/Jzzzin/spring-micro-study/
          searchPaths: licensingservice, organizationservice, zuulservice, specialroutesservice, authenticationservice
          username: Jzzzin
          password: GITHUBhedgehog3#

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.bloknoma: DEBUG

# eureka 설정
eureka:
  instance:
    prefer-ip-address: true # eureka 에 등록할 서비스의 이름을 host name 이 아닌 ip 주소로 등록
  client:
    register-with-eureka: true # eureka 에 서비스 등록
    fetch-registry: true # eureka registry 캐싱
    service-url:
      defaultZone: http://localhost:8761/eureka/ # eureka 서비스 위치
