#Default port is 8761
server:
  port: 8761

# eureka
eureka:
  client:
    register-with-eureka: false # eureka service 등록
    fetch-registry: false # eureka registry 캐싱
    service-url:
      defaultZone: http://localhost:8761/eureka/ # eureka location /eureka/ 붙여야 됨
  server:
    wait-time-in-ms-when-sync-empty: 30
    enable-self-preservation: false # 자기 보호 모드 비활성화 (클라이언트 셧다운 시 등록해제 실행)

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.bloknoma: DEBUG


