server:
  port: 5555

#actuator 모든 경로 노출, zuul routes 경로 확인 위해서 필요
management:
  endpoints:
    web:
      exposure:
        include: "*"

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.bloknoma: DEBUG

eureka:
  instance:
    prefer-ip-address: true # eureka 에 등록할 서비스의 이름을 host name 이 아닌 ip 주소로 등록
  client:
    register-with-eureka: true # eureka service 등록
    fetch-registry: true # eurek registry 캐싱
    service-url:
      defaultZone: http://localhost:8761/eureka/

#zuul:
#  prefix: /api # 서비스 접두어 설정
#  routes: # 수동 경로 매핑
#    licensingservice: /licensing/**



