#Default port is 8761
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    # eureka 에 서비스 등록
    fetch-registry: false
    # eureka registry 캐싱
  server:
    wait-time-in-ms-when-sync-empty: 5
    # eureka 시작 시 등록대기시간 설정
  serviceUrl:
    defaultZone: http://localhost:8761
    # eureka 서비스 위치