version:  '2'
services:
  configserver:
    extends:
      file: ../common/docker-compose.yml
      service: configserver
  database:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      POSTGRES_USER: "postgres_prod"
      POSTGRES_PASSWORD: "p0stgr@s_prod"
      POSTGRES_DB: "eagle_eye_prod"
  licensingservice:
      image: jin/bn-licensing-service:ch03
      ports:
        - "8080:8080"
      environment:
        PROFILE: "prod"
        CONFIGSERVER_URI: "http://configserver:8888"
        CONFIGSERVER_PORT: "8888"
        DATABASESERVER_PORT: "5432"
        ENCRYPT_KEY: "IMSYMMETRIC"