server:
  port: 8085

spring:
  zipkin:
    baseUrl: http://localhost:9411 # zipkin location http:// 붙여야 됨
#  sleuth:
#    sampler:
#      probability: 1 # zipkin sampling frequency always
  cloud:
    stream:
      bindings:
        outboundOrgChanges: # channel name
          destination: orgChangeTopic # message queue(topic) name
          content-type: application/json # message type
      kafka: # kafka use
        binder:
#          zkNodes: localhost # zookeeper location
          brokers: localhost # kafka location

#JWT tokenservice 사용 시 auth uri 호출하지 않는다
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:8901/auth/user

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.bloknoma: DEBUG
#  file: c:/Workspace/log/organization/application.log # nxlog log 수집 위치, logback 설정을 사용하는게 낫다

eureka:
  instance:
    prefer-ip-address: true # eureka 호스트 네임에 ip 등록
  client:
    register-with-eureka: true # eureka 서비스 등록
    fetch-registry: true # eureka registry 캐싱
    service-url:
      defaultZone: http://localhost:8761/eureka/ # eureka 서비스 위치
