server:
  port: 5555

#actuator 모든 경로 노출, zuul routes 경로 확인 위해서 필요
management:
  endpoints:
    web:
      exposure:
        include: "*"

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.bloknoma: DEBUG
  file: c:/Workspace/log/zuul/application.log # nxlog log 수집 위치, logback 설정을 사용하는게 낫다

eureka:
  instance:
    prefer-ip-address: true # eureka 에 등록할 서비스의 이름을 host name 이 아닌 ip 주소로 등록
  client:
    register-with-eureka: true # eureka service 등록
    fetch-registry: true # eurek registry 캐싱
    service-url:
      defaultZone: http://localhost:8761/eureka/

#slueth & zipkin
spring:
  sleuth:
    propagation-keys: Authorization # Auth token propagation
#    sampler:
#      probability: 1 # zipkin sampling frequency always
  zipkin:
    baseUrl: http://localhost:9411 # zipkin location http:// 붙여야 됨

#zuul:
#  prefix: /api # 서비스 접두어 설정
#  routes: # 수동 경로 매핑
#    licensingservice: /licensing/**



