eureka:
  instance:
    prefer-ip-address: true # eureka host name ip로 등록
  client:
    register-with-eureka: true # eureka service 등록
    fetch-registry: true # eureka registry 캐싱
    service-url:
      defaultZone: http://localhost:8761/eureka/ #eureka service 위치
#Setting the logging levels for the service
logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    com.bloknoma: DEBUG

server:
  error:
    include-exception: true
